apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: medilink
type: Opaque
stringData:
  DB_NAME: medilink_db
  DB_USER: medilink
  DB_PASSWORD: medilink_password
  DB_HOST: postgres-service
  DB_PORT: "5432"
