# Generated by Django 5.2.7 on 2025-10-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_reset_password_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='license_number',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
