# Generated by Django 5.2.7 on 2025-10-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_pharmacy_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
