# Generated by Django 4.2.25 on 2025-11-03 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appointment_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacistStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.pharmacy')),
            ],
            options={
                'unique_together': {('pharmacy', 'email')},
            },
        ),
    ]
