apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: medilink
  labels:
    app: api-gateway
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: api-gateway
