apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: medilink
  labels:
    app: notification-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8007
    targetPort: 8007
    protocol: TCP
    name: http

  selector:
    app: notification-service
