apiVersion: v1
kind: Service
metadata:
  name: pharmacy-service
  namespace: medilink
  labels:
    app: pharmacy-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8004
    targetPort: 8004
    protocol: TCP
    name: http

  selector:
    app: pharmacy-service
