apiVersion: v1
kind: Service
metadata:
  name: scheduling-service
  namespace: medilink
  labels:
    app: scheduling-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8005
    targetPort: 8005
    protocol: TCP
    name: http

  selector:
    app: scheduling-service
